---
linters:
  disable-all: true
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # additional
    - gofmt
    - gosec
    - godot
    - revive
    - wsl
    - paralleltest
    - prealloc
    - testifylint

linters-settings:
  testifylint:
    # Enable all checkers (https://github.com/Antonboom/testifylint#checkers).
    # Default: false
    enable-all: true
