with-expecter: true
dir: ./internal/mocks
outpkg: mocks
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
packages:
  gitlab.com/egg-be/egg-backend/internal/service:
    interfaces:
      RedisInterface:
      DBInterface:
