apiVersion: v1
kind: ConfigMap
metadata:
  name: egg-backend-config
data:
  RUNTIME: "development"
  JWT_TTL: "24h"
  RULES_PATH: "/etc/egg/rules.yml"
  REDIS_ENABLED: "true"
  REDIS_URI: ${REDIS_URI}