apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  uri: mongodb+srv://doadmin:Z6O9743j1G8yNxC0@db-mongodb-fra1-73737-00baa3ad.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=db-mongodb-fra1-73737&tls=true